#!/usr/bin/env bash
# kb-changelog-rollup.sh
# Produce a recent-changes report for the last 1 day and 7 days.
# Usage: kb-changelog-rollup.sh [--dry-run]
set -euo pipefail

DRY_RUN="${1:-}"
HOST=$(hostname -s)
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
TODAY=$(date +%Y-%m-%d)
KB_ROOT="/home/slimy/kb"
OUT_FILE="$KB_ROOT/output/changelog-$TIMESTAMP.md"

# Source webhook config if present (category: CHANGELOG)
if [[ -f ~/.config/slimy/webhooks.env ]]; then
    source ~/.config/slimy/webhooks.env
fi
DISCORD_WEBHOOK="${DISCORD_WEBHOOK_CHANGELOG:-}"

mkdir -p "$KB_ROOT/output"

# Known project paths
declare -A PROJECTS=(
    ["slimy-kb"]="/home/slimy/kb"
    ["slimy-monorepo"]="/opt/slimy/slimy-monorepo"
    ["mission-control"]="/home/slimy/mission-control"
    ["pm-updown-bot-bundle"]="/home/slimy/pm_updown_bot_bundle"
    ["clawd"]="/home/slimy/clawd"
    ["agents-harness"]="/home/slimy/.claude/agents"
    ["slimyai-setup"]="/opt/slimy/app"
    ["workspace-openclaw"]="/home/slimy/.openclaw/workspace"
    ["mailbox-ingest"]="/home/slimy/nuc-comms/mailbox_ingest"
)

ONE_DAY_AGO=$(date -d yesterday +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d 2>/dev/null || echo "$(date +%Y)-$(date +%m)-$(($(date +%d) - 1))")
SEVEN_DAYS_AGO=$(date -d '7 days ago' +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d 2>/dev/null || echo "$(date +%Y)-$(date +%m)-$(($(date +%d) - 7))")

{
    echo "# Changelog Rollup — $TODAY $HOST"
    echo ""
    echo "> Auto-generated by kb-changelog-rollup.sh"
    echo ""
    echo "## Last 24 Hours"
    echo ""

    activity_found=false
    for key in "${!PROJECTS[@]}"; do
        path="${PROJECTS[$key]}"
        if [[ ! -d "$path" ]] || ! git -C "$path" rev-parse --git-dir >/dev/null 2>&1; then
            continue
        fi

        commits=$(git -C "$path" log --since="$ONE_DAY_AGO" --oneline 2>/dev/null || true)
        if [[ -n "$commits" ]]; then
            activity_found=true
            echo "### $key"
            echo '```'
            echo "$commits"
            echo '```'
            echo ""
        fi
    done

    if [[ "$activity_found" == "false" ]]; then
        echo "*No commits in the last 24 hours.*"
        echo ""
    fi

    echo "## Last 7 Days"
    echo ""

    activity_found=false
    for key in "${!PROJECTS[@]}"; do
        path="${PROJECTS[$key]}"
        if [[ ! -d "$path" ]] || ! git -C "$path" rev-parse --git-dir >/dev/null 2>&1; then
            continue
        fi

        commits=$(git -C "$path" log --since="$SEVEN_DAYS_AGO" --oneline 2>/dev/null || true)
        if [[ -n "$commits" ]]; then
            activity_found=true
            echo "### $key"
            echo '```'
            echo "$commits"
            echo '```'
            echo ""
        fi
    done

    if [[ "$activity_found" == "false" ]]; then
        echo "*No commits in the last 7 days.*"
        echo ""
    fi

    echo "## Notes"
    echo "- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "- Host: $HOST"
} > "$OUT_FILE"

echo "[kb-changelog-rollup] Wrote $OUT_FILE"

# Optional Discord webhook (category: CHANGELOG)
if [[ -n "${DISCORD_WEBHOOK:-}" ]]; then
    if [[ "$DRY_RUN" != "--dry-run" ]]; then
        msg="Changelog rollup $TODAY on $HOST"
        curl -s -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$msg\"}" >/dev/null 2>&1 \
            && echo "[kb-changelog-rollup] Posted Discord webhook" \
            || echo "[kb-changelog-rollup] Discord webhook post failed (non-critical)"
    else
        echo "[kb-changelog-rollup] DRY-RUN: would post Discord webhook"
    fi
else
    echo "[kb-changelog-rollup] DISCORD_WEBHOOK_CHANGELOG not configured — skipping Discord post"
fi
