#!/usr/bin/env bash
# kb-recommend.sh
# Scan wiki, raw, recent changes, anomalies and generate recommendations.
# Usage: kb-recommend.sh [--dry-run]
set -euo pipefail

DRY_RUN="${1:-}"
HOST=$(hostname -s)
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
TODAY=$(date +%Y-%m-%d)
KB_ROOT="/home/slimy/kb"
OUT_FILE="$KB_ROOT/output/recommend-$TIMESTAMP.md"
VAULT_REC_DAILY="/home/slimy/obsidian/slimyai-vault/Recommendations/Daily"

# Source webhook config if present (category: RECOMMEND)
if [[ -f ~/.config/slimy/webhooks.env ]]; then
    source ~/.config/slimy/webhooks.env
fi
DISCORD_WEBHOOK="${DISCORD_WEBHOOK_RECOMMEND:-}"

mkdir -p "$KB_ROOT/output" "$VAULT_REC_DAILY"

# Collect compile candidates
mapfile -t compile_candidates < <(find "$KB_ROOT/raw" -type f -name '*.md' -mtime -7 -printf '%P\n' 2>/dev/null | sort || true)
candidate_count=${#compile_candidates[@]}

# Collect stale articles
stale_articles=()
if [[ -f "$KB_ROOT/wiki/_stale.md" ]]; then
    while IFS= read -r line; do
        [[ -n "$line" ]] && stale_articles+=("$line")
    done < <(grep -E '^\[|^-' "$KB_ROOT/wiki/_stale.md" 2>/dev/null | head -20)
fi
stale_count=${#stale_articles[@]}

# Collect conflict files
conflict_count=$(find "$KB_ROOT" "$VAULT_REC_DAILY" -type f -iname '*conflict*' 2>/dev/null | wc -l | tr -d ' ')

# Check repos missing README/CHANGELOG/VERSION
declare -A PROJECTS=(
    ["slimy-kb"]="/home/slimy/kb"
    ["slimy-monorepo"]="/opt/slimy/slimy-monorepo"
    ["mission-control"]="/home/slimy/mission-control"
    ["pm-updown-bot-bundle"]="/home/slimy/pm_updown_bot_bundle"
    ["clawd"]="/home/slimy/clawd"
    ["agents-harness"]="/home/slimy/.claude/agents"
    ["slimyai-setup"]="/opt/slimy/app"
    ["workspace-openclaw"]="/home/slimy/.openclaw/workspace"
    ["mailbox-ingest"]="/home/slimy/nuc-comms/mailbox_ingest"
)

missing_docs_repos=()
for key in "${!PROJECTS[@]}"; do
    path="${PROJECTS[$key]}"
    [[ ! -d "$path" ]] && continue
    missing=""
    [[ ! -f "$path/README.md" ]] && missing="${missing}README "
    [[ ! -f "$path/CHANGELOG.md" ]] && missing="${missing}CHANGELOG "
    [[ ! -f "$path/VERSION.md" ]] && missing="${missing}VERSION "
    [[ -n "$missing" ]] && missing_docs_repos+=("$key: missing $missing")
done

# Failed systemd services
failed_svcs=""
for svc in slimy-web-health slimy-report; do
    if systemctl --user is-failed "$svc" 2>/dev/null | grep -q failed; then
        failed_svcs="$failed_svcs $svc"
    fi
done

# KB gaps — articles that should exist per discovery doc
declare -A expected_wiki=(
    ["chriss-agent"]="/home/slimy/chriss-agent"
    ["slimyai-setup"]="/opt/slimy/app"
    ["slimy-kb"]="/home/slimy/kb"
)
missing_wiki_articles=()
for article in "${!expected_wiki[@]}"; do
    if [[ ! -f "$KB_ROOT/wiki/projects/${article}.md" ]] && [[ -d "${expected_wiki[$article]}" ]]; then
        missing_wiki_articles+=("$article")
    fi
done

# Build recommendations
recommendations=()
type_count=0

add_rec() {
    local type="$1"
    local priority="$2"
    local title="$3"
    local body="$4"
    recommendations+=("$type|$priority|$title|$body")
    ((type_count++))
}

if [[ "$candidate_count" -gt 0 ]]; then
    add_rec "additions" "high" "Compile unprocessed raw files" \
        "$candidate_count raw files not referenced by wiki. Run: \`wiki compile-candidates\` then \`wiki prompt-compile\`"
fi

if [[ ${#missing_wiki_articles[@]} -gt 0 ]]; then
    add_rec "missing-docs" "high" "Create missing wiki project articles" \
        "Missing wiki articles: ${missing_wiki_articles[*]}. These projects exist on disk but have no wiki coverage."
fi

if [[ ${#missing_docs_repos[@]} -gt 0 ]]; then
    add_rec "missing-docs" "medium" "Scaffold missing project docs" \
        "$(printf '%s; ' "${missing_docs_repos[@]}")"
fi

if [[ "$conflict_count" -gt 0 ]]; then
    add_rec "backlog" "high" "Resolve conflict files" \
        "$conflict_count conflict file(s) found. Run: \`wiki conflicts\` and resolve before next compile."
fi

if [[ -n "$failed_svcs" ]]; then
    add_rec "refactors" "medium" "Investigate failed systemd services" \
        "Failed services:${failed_svcs}. Check: \`systemctl --user status <svc>\`"
fi

if [[ "$stale_count" -gt 5 ]]; then
    add_rec "legacy-cleanup" "low" "Refresh stale wiki articles" \
        "$stale_count stale articles detected. Consider running a full wiki refresh."
fi

if [[ ${#recommendations[@]} -eq 0 ]]; then
    recommendations+=("general|none|No action items detected.|KB is healthy; no urgent recommendations.")
fi

{
    echo "# Recommendations — $TODAY $HOST"
    echo ""
    echo "> Auto-generated by kb-recommend.sh | Timestamp: $TIMESTAMP"
    echo ""
    echo "## Summary"
    echo ""
    echo "| Type | Priority | Count |"
    echo "|---|---|---|"
    echo "| Additions | HIGH | $(printf '%s\n' "${recommendations[@]}" | grep -c '^additions|') |"
    echo "| Missing Docs | HIGH/MED | $(printf '%s\n' "${recommendations[@]}" | grep -c '^missing-docs|') |"
    echo "| Backlog | MED | $(printf '%s\n' "${recommendations[@]}" | grep -c '^backlog|') |"
    echo "| Refactors | MED | $(printf '%s\n' "${recommendations[@]}" | grep -c '^refactors|') |"
    echo "| Legacy Cleanup | LOW | $(printf '%s\n' "${recommendations[@]}" | grep -c '^legacy-cleanup|') |"
    echo ""
    echo "## Recommendations"
    echo ""

    idx=1
    for rec in "${recommendations[@]}"; do
        IFS='|' read -r type priority title body <<< "$rec"
        echo "### $idx. [$priority] $title"
        echo "> Type: $type"
        echo ""
        echo "$body"
        echo ""
        ((idx++))
    done

    echo "## Metadata"
    echo "- Compile candidates: $candidate_count"
    echo "- Stale articles: $stale_count"
    echo "- Conflict files: $conflict_count"
    echo "- Host: $HOST"
} > "$OUT_FILE"

echo "[kb-recommend] Wrote $OUT_FILE"

# Also write vault daily recommendation
VAULT_OUT="$VAULT_REC_DAILY/${TODAY}-${HOST}.md"
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    cat > "$VAULT_OUT" << EOF
# Recommendations — $TODAY

> Host: $HOST | Type: Daily | Generated: $(date -u +%H:%M:%S)

## Quick Summary
| Metric | Value |
|---|---|
| Compile candidates | $candidate_count |
| Stale articles | $stale_count |
| Conflict files | $conflict_count |

## Top Actions
$(local i=1; for rec in "${recommendations[@]}"; do IFS='|' read -r type priority title body <<< "$rec"; echo "$i. **[$priority]** $title — $body"; ((i++)); done)

---
*Auto-generated by kb-recommend.sh*
EOF
    echo "[kb-recommend] Wrote vault recommendation: $VAULT_OUT"
fi

# Optional Discord webhook (category: RECOMMEND)
if [[ -n "${DISCORD_WEBHOOK:-}" ]]; then
    if [[ "$DRY_RUN" != "--dry-run" ]]; then
        top_rec=""
        if [[ ${#recommendations[@]} -gt 0 ]]; then
            IFS='|' read -r _ priority title _ <<< "${recommendations[0]}"
            top_rec=" [$priority] $title"
        fi
        msg="Recommendations $TODAY on $HOST — ${candidate_count} compile candidates, ${conflict_count} conflicts, ${stale_count} stale${top_rec}"
        curl -s -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$msg\"}" >/dev/null 2>&1 \
            && echo "[kb-recommend] Posted Discord webhook" \
            || echo "[kb-recommend] Discord webhook post failed (non-critical)"
    else
        echo "[kb-recommend] DRY-RUN: would post Discord webhook"
    fi
else
    echo "[kb-recommend] DISCORD_WEBHOOK_RECOMMEND not configured — skipping Discord post"
fi

echo "[kb-recommend] Done."
