#!/usr/bin/env bash
# kb-todo.sh
# Create a practical operator checklist for today.
# Usage: kb-todo.sh [--dry-run]
set -euo pipefail

DRY_RUN="${1:-}"
HOST=$(hostname -s)
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
TODAY=$(date +%Y-%m-%d)
KB_ROOT="/home/slimy/kb"
OUT_FILE="$KB_ROOT/output/todo-$TIMESTAMP.md"
VAULT_DAILY="/home/slimy/obsidian/slimyai-vault/Daily/${TODAY}.md"

# Source webhook config if present (category: DAILY)
if [[ -f ~/.config/slimy/webhooks.env ]]; then
    source ~/.config/slimy/webhooks.env
fi
DISCORD_WEBHOOK="${DISCORD_WEBHOOK_DAILY:-}"

mkdir -p "$KB_ROOT/output"

# Gather state
conflict_count=$(find "$KB_ROOT" -type f -iname '*conflict*' 2>/dev/null | wc -l | tr -d ' ')
uncompiled_count=$(find "$KB_ROOT/raw" -type f -name '*.md' -mtime -7 2>/dev/null | wc -l | tr -d ' ')
stale_count=0
if [[ -f "$KB_ROOT/wiki/_stale.md" ]]; then
    count1=$(grep -c '^\[' "$KB_ROOT/wiki/_stale.md" 2>/dev/null || true)
    count2=$(grep -c '^- ' "$KB_ROOT/wiki/_stale.md" 2>/dev/null || true)
    stale_count=$(( count1 > count2 ? count1 : count2 ))
fi

# Check repos missing README/CHANGELOG/VERSION
declare -A PROJECTS=(
    ["slimy-kb"]="/home/slimy/kb"
    ["slimy-monorepo"]="/opt/slimy/slimy-monorepo"
    ["mission-control"]="/home/slimy/mission-control"
    ["pm-updown-bot-bundle"]="/home/slimy/pm_updown_bot_bundle"
    ["clawd"]="/home/slimy/clawd"
    ["agents-harness"]="/home/slimy/.claude/agents"
    ["slimyai-setup"]="/opt/slimy/app"
    ["workspace-openclaw"]="/home/slimy/.openclaw/workspace"
    ["mailbox-ingest"]="/home/slimy/nuc-comms/mailbox_ingest"
)

missing_docs_repos=()
for key in "${!PROJECTS[@]}"; do
    path="${PROJECTS[$key]}"
    [[ ! -d "$path" ]] && continue
    missing=""
    [[ ! -f "$path/README.md" ]] && missing="${missing}README "
    [[ ! -f "$path/CHANGELOG.md" ]] && missing="${missing}CHANGELOG "
    [[ ! -f "$path/VERSION.md" ]] && missing="${missing}VERSION "
    [[ -n "$missing" ]] && missing_docs_repos+=("- $key: missing ${missing}")
done

# Service health
service_status=()
for svc in mission-control slimy-web slimy-mysql-tunnel nuc-mailbox-ingest openclaw-gateway; do
    status=$(systemctl --user is-active "$svc" 2>/dev/null || echo "unknown")
    marker="[ ]"
    [[ "$status" == "active" ]] && marker="[x]"
    service_status+=("$marker $svc: $status")
done

# Failed services
failed_svcs=""
for svc in slimy-web-health slimy-report; do
    if systemctl --user is-failed "$svc" 2>/dev/null | grep -q failed; then
        failed_svcs="$failed_svcs - $svc (FAILED)\n"
    fi
done

# Compile candidate list
compile_list=""
if [[ "$uncompiled_count" -gt 0 ]]; then
    compile_list=$(find "$KB_ROOT/raw" -type f -name '*.md' -mtime -7 2>/dev/null | sed "s|$KB_ROOT/||" | head -20 | sed 's/^/  - /')
fi

{
    echo "# Operator Todo — $TODAY $HOST"
    echo ""
    echo "> Auto-generated by kb-todo.sh | Timestamp: $TIMESTAMP"
    echo ""
    echo "## Service Health"
    echo ""
    for s in "${service_status[@]}"; do
        echo "$s"
    done
    [[ -n "$failed_svcs" ]] && echo -e "\n## FAILED Services\n$failed_svcs"
    echo ""
    echo "## Conflict Files"
    if [[ "$conflict_count" -gt 0 ]]; then
        echo "- [ ] Resolve $conflict_count conflict file(s): \`wiki conflicts\`"
    else
        echo "- [x] No conflict files detected"
    fi
    echo ""
    echo "## Compile Candidates ($uncompiled_count)"
    if [[ -n "$compile_list" ]]; then
        echo "\`\`\`"
        echo "$compile_list"
        echo "\`\`\`"
        echo "- [ ] Run: \`wiki prompt-compile\` to process"
    else
        echo "- [x] No compile candidates"
    fi
    echo ""
    echo "## Stale Articles ($stale_count)"
    if [[ "$stale_count" -gt 0 ]]; then
        echo "- [ ] Refresh stale articles: \`wiki status\` then review \`wiki/_stale.md\`"
    else
        echo "- [x] No stale articles detected"
    fi
    echo ""
    echo "## Missing Project Docs"
    if [[ ${#missing_docs_repos[@]} -gt 0 ]]; then
        for repo in "${missing_docs_repos[@]}"; do
            echo "$repo"
        done
        echo "- [ ] Run: \`for r in /home/slimy/kb /opt/slimy/slimy-monorepo ...; do bash /home/slimy/kb/tools/kb-project-doc-sync.sh \$r; done\`"
    else
        echo "- [x] All known projects have README/CHANGELOG/VERSION"
    fi
    echo ""
    echo "## Today's Checklist"
    echo "- [ ] Run: \`wiki status\`"
    echo "- [ ] Review Discord/Telegram for overnight alerts"
    echo "- [ ] Check morning brief output if configured"
    echo ""
    echo "## Recommendation Follow-ups"
    echo "- Run: \`wiki recommend\` for full prioritized list"
} > "$OUT_FILE"

echo "[kb-todo] Wrote $OUT_FILE"

# Update vault daily checklist section if it exists
if [[ -f "$VAULT_DAILY" ]]; then
    if [[ "$DRY_RUN" != "--dry-run" ]]; then
        # Inject/replace project checklist section
        in_section=false
        section_line=""
        while IFS= read -r line; do
            if [[ "$line" =~ ^##\ Project\ Checklist ]]; then
                in_section=true
                section_line="$line"
                echo "$line"
                echo "- [ ] Review compile candidates"
                echo "- [ ] Check for conflict files"
                echo "- [ ] Verify slimy-web.service status"
                echo "- [ ] Verify mission-control.service status"
                echo "- [ ] Run knowledge base sync"
            elif [[ "$in_section" == true && "$line" =~ ^##\  ]]; then
                in_section=false
                echo "$line"
            elif [[ "$in_section" == false ]]; then
                echo "$line"
            fi
        done < "$VAULT_DAILY" > "${VAULT_DAILY}.tmp"
        mv "${VAULT_DAILY}.tmp" "${VAULT_DAILY}"
        echo "[kb-todo] Updated vault daily: $VAULT_DAILY"
    fi
fi

# Optional Discord webhook (category: DAILY)
if [[ -n "${DISCORD_WEBHOOK:-}" ]]; then
    if [[ "$DRY_RUN" != "--dry-run" ]]; then
        msg="Todo $TODAY on $HOST — conflicts: ${conflict_count}, compile: ${uncompiled_count}, stale: ${stale_count}"
        curl -s -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$msg\"}" >/dev/null 2>&1 \
            && echo "[kb-todo] Posted Discord webhook" \
            || echo "[kb-todo] Discord webhook post failed (non-critical)"
    else
        echo "[kb-todo] DRY-RUN: would post Discord webhook"
    fi
else
    echo "[kb-todo] DISCORD_WEBHOOK_DAILY not configured — skipping Discord post"
fi

echo "[kb-todo] Done. Output: $OUT_FILE"
