#!/usr/bin/env bash
# kb-version-scan.sh
# Scan known projects and generate a rollup of git state + runtime versions.
# Usage: kb-version-scan.sh [--dry-run]
set -euo pipefail

DRY_RUN="${1:-}"
HOST=$(hostname -s)
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
TODAY=$(date +%Y-%m-%d)
KB_ROOT="/home/slimy/kb"
OUTPUT_DIR="$KB_ROOT/output"
RAW_VERSIONS="$KB_ROOT/raw/versions"
OUT_FILE="$OUTPUT_DIR/versions-$TIMESTAMP.md"
RAW_OUT="$RAW_VERSIONS/${TODAY}-${HOST}-version-scan.md"

# Source webhook config if present (category: CHANGELOG)
if [[ -f ~/.config/slimy/webhooks.env ]]; then
    source ~/.config/slimy/webhooks.env
fi
DISCORD_WEBHOOK="${DISCORD_WEBHOOK_CHANGELOG:-}"

mkdir -p "$OUTPUT_DIR" "$RAW_VERSIONS"

# Known project paths
declare -A PROJECTS=(
    ["slimy-kb"]="/home/slimy/kb"
    ["slimy-monorepo"]="/opt/slimy/slimy-monorepo"
    ["mission-control"]="/home/slimy/mission-control"
    ["pm-updown-bot-bundle"]="/home/slimy/pm_updown_bot_bundle"
    ["clawd"]="/home/slimy/clawd"
    ["agents-harness"]="/home/slimy/.claude/agents"
    ["slimyai-setup"]="/opt/slimy/app"
    ["workspace-openclaw"]="/home/slimy/.openclaw/workspace"
    ["mailbox-ingest"]="/home/slimy/nuc-comms/mailbox_ingest"
)

scan_project() {
    local key="$1"
    local path="$2"

    if [[ ! -d "$path" ]]; then
        echo "| $key | — | — | — | $HOST | NOT FOUND |"
        return
    fi

    if ! git -C "$path" rev-parse --git-dir >/dev/null 2>&1; then
        echo "| $key | — | — | — | $HOST | NON_GIT |"
        return
    fi

    local branch commit last_date remote
    branch=$(git -C "$path" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
    commit=$(git -C "$path" rev-parse --short HEAD 2>/dev/null || echo "unknown")
    last_date=$(git -C "$path" log -1 --format=%ci 2>/dev/null | cut -d' ' -f1 || echo "unknown")
    remote=$(git -C "$path" remote get-url origin 2>/dev/null | sed 's|git@github.com:||;s|\.git$||' || echo "none")

    # Runtime clues
    local runtime="—"
    if [[ -f "$path/package.json" ]]; then
        local node_ver
        node_ver=$(grep '"node"' "$path/package.json" 2>/dev/null | sed 's/.*"node": *"\([^"]*\)".*/\1/' || true)
        [[ -n "$node_ver" ]] && runtime="node: $node_ver"
    fi
    if [[ -f "$path/pyproject.toml" ]]; then
        runtime="Python (pyproject.toml)"
    fi

    # Dirty check
    local dirty
    dirty=$(git -C "$path" status --porcelain | grep -v '^??' | wc -l | tr -d ' ')
    local dirty_flag=""
    [[ "$dirty" -gt 0 ]] && dirty_flag=" ($dirty uncommitted)"

    echo "| $key | $branch | \`$commit\` | $last_date | $HOST | $runtime$dirty_flag |"
}

{
    echo "# Version Scan — $TODAY $HOST"
    echo ""
    echo "> Auto-generated by kb-version-scan.sh | Output: \`$OUT_FILE\`"
    echo ""
    echo "## Project State Matrix"
    echo ""
    echo "| Project | Branch | Commit | Last Commit | Host | Runtime |"
    echo "|---|---|---|---|---|---|"

    for key in "${!PROJECTS[@]}"; do
        scan_project "$key" "${PROJECTS[$key]}"
    done

    echo ""
    echo "## Notes"
    echo "- Scanned: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "- Host: $HOST"
    echo "- See also: raw/versions/ for source notes"
} > "$OUT_FILE"

echo "[kb-version-scan] Wrote $OUT_FILE"

# Also write the raw source file
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    cp "$OUT_FILE" "$RAW_OUT"
    echo "[kb-version-scan] Wrote $RAW_OUT"
fi

echo "[kb-version-scan] Done. Output: $OUT_FILE"

# Optional Discord webhook (category: CHANGELOG)
if [[ -n "${DISCORD_WEBHOOK:-}" ]]; then
    if [[ "$DRY_RUN" != "--dry-run" ]]; then
        msg="Version scan $TODAY on $HOST"
        curl -s -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$msg\"}" >/dev/null 2>&1 \
            && echo "[kb-version-scan] Posted Discord webhook" \
            || echo "[kb-version-scan] Discord webhook post failed (non-critical)"
    else
        echo "[kb-version-scan] DRY-RUN: would post Discord webhook"
    fi
else
    echo "[kb-version-scan] DISCORD_WEBHOOK_CHANGELOG not configured — skipping Discord post"
fi
