#!/usr/bin/env bash
# slimy-agent-finish.sh
# Single end-of-run automation entrypoint for Claude and Codex agents.
# Prevents recursion via SLIMY_AUTOFINISH_ACTIVE=1 env var.
#
# Usage:
#   slimy-agent-finish.sh --agent claude|codex|unknown [--repo /path/to/repo] [--summary "text"] [--dry-run] [--skip-compile]
set -euo pipefail

# Guard against recursion
if [[ "${SLIMY_AUTOFINISH_ACTIVE:-0}" == "1" ]]; then
    echo "[slimy-agent-finish] RECURSION GUARD: SLIMY_AUTOFINISH_ACTIVE=1 — exiting to prevent loop"
    exit 0
fi
export SLIMY_AUTOFINISH_ACTIVE=1

# Parse args
AGENT="unknown"
DRY_RUN=""
SKIP_COMPILE=""
declare -a REPOS=()
SUMMARY=""
HOST=$(hostname -s)
TODAY=$(date +%Y-%m-%d)
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
KB_ROOT="/home/slimy/kb"
KB_TOOLS="$KB_ROOT/tools"

# Source webhook config if present
if [[ -f ~/.config/slimy/webhooks.env ]]; then
    source ~/.config/slimy/webhooks.env
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --agent)
            AGENT="$2"; shift 2 ;;
        --repo)
            REPOS+=("$2"); shift 2 ;;
        --summary)
            SUMMARY="$2"; shift 2 ;;
        --dry-run)
            DRY_RUN="--dry-run"; shift ;;
        --skip-compile)
            SKIP_COMPILE="1"; shift ;;
        --)
            shift; break ;;
        -*)
            echo "[slimy-agent-finish] Unknown option: $1"; shift ;;
        *)
            break ;;
    esac
done

echo "[slimy-agent-finish] Starting finish automation..."
echo "[slimy-agent-finish] Agent: $AGENT | Host: $HOST | Dry-run: $DRY_RUN | Skip-compile: $SKIP_COMPILE"
echo "[slimy-agent-finish] Repos: ${REPOS[*]:-none specified (will detect)}"

# Detect recently changed git repos if none specified
if [[ ${#REPOS[@]} -eq 0 ]]; then
    echo "[slimy-agent-finish] No repos specified — detecting recently changed repos under /home/slimy and /opt/slimy..."
    declare -A SEEN=()
    # Look for git repos with commits in the last 24 hours
    for dir in /home/slimy /opt/slimy; do
        [[ -d "$dir" ]] || continue
        while IFS= read -r gitdir; do
            repo="${gitdir%/.git}"
            # Skip KB itself to avoid circular reference
            [[ "$repo" == "$KB_ROOT" ]] && continue
            # Avoid duplicates
            if [[ -z "${SEEN[$repo]:-}" ]]; then
                SEEN["$repo"]=1
                # Check if it has commits in last 24h
                if git -C "$repo" log --since="24 hours ago" -q 2>/dev/null; then
                    REPOS+=("$repo")
                fi
            fi
        done < <(find "$dir" -maxdepth 4 -name ".git" -type d 2>/dev/null | sed 's/\/.git$//')
    done
    echo "[slimy-agent-finish] Detected ${#REPOS[@]} recently-changed repo(s): ${REPOS[*]:-none}"
fi

# Run kb-project-doc-sync for each repo
for repo in "${REPOS[@]}"; do
    if [[ -d "$repo" ]]; then
        echo "[slimy-agent-finish] Syncing project docs: $repo"
        bash "$KB_TOOLS/kb-project-doc-sync.sh" "$repo" "$DRY_RUN"
    else
        echo "[slimy-agent-finish] WARNING: repo not found: $repo"
    fi
done

# Write agent learnings KB raw note
RAW_LEARNINGS="$KB_ROOT/raw/agent-learnings/${TODAY}-${HOST}-${AGENT}-summary.md"
mkdir -p "$KB_ROOT/raw/agent-learnings"
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    cat > "$RAW_LEARNINGS" << EOF
---
name: ${TODAY}-${HOST}-${AGENT}-summary
description: ${AGENT} agent session summary for ${TODAY} on ${HOST}
type: agent-learning
---

# ${AGENT} Agent Session — ${TODAY} ${HOST}

> Agent: ${AGENT} | Host: ${HOST} | Timestamp: ${TIMESTAMP}

## Session Summary
${SUMMARY:-No summary provided.}

## Repos Touched
$(for repo in "${REPOS[@]:-}"; do echo "- $repo"; done)

## Notable Changes
${SUMMARY:-—}

## Next Steps
${SUMMARY:-—}

---
*Auto-generated by slimy-agent-finish.sh*
EOF
    echo "[slimy-agent-finish] Wrote agent learnings: $RAW_LEARNINGS"
else
    echo "[slimy-agent-finish] DRY-RUN: would write agent learnings to $RAW_LEARNINGS"
fi

# Write KB raw changelog note
RAW_CHANGELOG="$KB_ROOT/raw/changelogs/${TODAY}-${HOST}-project-changelog.md"
mkdir -p "$KB_ROOT/raw/changelogs"
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    cat > "$RAW_CHANGELOG" << EOF
---
name: ${TODAY}-${HOST}-project-changelog
description: Agent-triggered changelog for ${TODAY} on ${HOST}
type: changelog
---

# Changelog — ${TODAY} ${HOST}

> Agent: ${AGENT} | Host: ${HOST}

## Repos Updated
$(for repo in "${REPOS[@]:-}"; do
    if git -C "$repo" rev-parse --git-dir >/dev/null 2>&1; then
        branch=$(git -C "$repo" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "—")
        commit=$(git -C "$repo" rev-parse --short HEAD 2>/dev/null || echo "—")
        msg=$(git -C "$repo" log -1 --format="%s" 2>/dev/null || echo "—")
        echo "- \`$repo\` → \`$commit\` ($branch) — $msg"
    else
        echo "- $repo (non-git)"
    fi
done)

## Agent Summary
${SUMMARY:-—}

---
*Auto-generated by slimy-agent-finish.sh*
EOF
    echo "[slimy-agent-finish] Wrote changelog note: $RAW_CHANGELOG"
else
    echo "[slimy-agent-finish] DRY-RUN: would write changelog to $RAW_CHANGELOG"
fi

# Commit and push changed project repos (non-kb), track failures for ALERTS
ALERT_MSG=""
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    for repo in "${REPOS[@]:-}"; do
        [[ -d "$repo" ]] || continue
        [[ "$repo" == "$KB_ROOT" ]] && continue
        if git -C "$repo" rev-parse --git-dir >/dev/null 2>&1; then
            changes=$(git -C "$repo" status --porcelain 2>/dev/null || true)
            if [[ -n "$changes" ]]; then
                echo "[slimy-agent-finish] Committing changes in $repo..."
                if (
                    cd "$repo"
                    git add -A
                    git commit -m "docs: auto-sync project docs from ${HOST} ${TODAY}" 2>/dev/null && \
                    git push origin "$(git rev-parse --abbrev-ref HEAD)" 2>/dev/null
                ); then
                    echo "[slimy-agent-finish] Pushed $repo"
                else
                    echo "[slimy-agent-finish] WARNING: could not push $repo (may need credentials)"
                    ALERT_MSG="${ALERT_MSG}push failed: $repo; "
                fi
            else
                echo "[slimy-agent-finish] No changes to commit in $repo"
            fi
        fi
    done
fi

# Commit and push KB changes created before child compile ran
# (child compile handles its own sync/push at end; this captures pre-child artifacts only)
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    echo "[slimy-agent-finish] Committing KB changes..."
    # Check for any non-zero uncommitted changes (ignores child-cleaned temp files)
    KB_DIFF=$(cd "$KB_ROOT" && git add -A && git diff --cached --stat 2>&1 || true)
    if [[ -n "$KB_DIFF" && "$KB_DIFF" != " no changes added" ]]; then
        if git -C "$KB_ROOT" commit -m "kb: autofile $AGENT $(date +%Y%m%d-%H%M%S)" 2>&1; then
            echo "[slimy-agent-finish] KB committed: ${KB_DIFF:0:80}"
        else
            echo "[slimy-agent-finish] WARNING: KB commit failed"
            ALERT_MSG="${ALERT_MSG}KB commit failed; "
        fi
    else
        echo "[slimy-agent-finish] No pre-child KB changes to commit"
    fi
    # Push any remaining local commits (child compile will have pushed its own)
    KB_PUSHED=$(cd "$KB_ROOT" && git push origin main 2>&1 || true)
    if [[ "$KB_PUSHED" == *"error"* ]] || [[ "$KB_PUSHED" == *"fatal"* ]]; then
        echo "[slimy-agent-finish] WARNING: KB push had issues: ${KB_PUSHED:0:100}"
        ALERT_MSG="${ALERT_MSG}KB push had issues; "
    elif [[ -n "$KB_PUSHED" && "$KB_PUSHED" != *"Everything up-to-date"* ]]; then
        echo "[slimy-agent-finish] KB pushed: ${KB_PUSHED:0:80}"
    else
        echo "[slimy-agent-finish] KB push OK (up-to-date or synced by child)"
    fi
else
    echo "[slimy-agent-finish] DRY-RUN: would commit and push KB changes"
fi

# Run compile if not skipped, track failures for ALERTS
if [[ -z "$SKIP_COMPILE" && "$DRY_RUN" != "--dry-run" ]]; then
    echo "[slimy-agent-finish] Running compile check..."
    if ! bash "$KB_TOOLS/kb-compile-if-needed.sh" 2>&1; then
        echo "[slimy-agent-finish] WARNING: compile-if-needed returned non-zero"
        ALERT_MSG="${ALERT_MSG}compile-if-needed failed; "
    fi
elif [[ "$DRY_RUN" == "--dry-run" ]]; then
    echo "[slimy-agent-finish] DRY-RUN: skipping compile"
else
    echo "[slimy-agent-finish] SKIP_COMPILE set — skipping compile"
fi

# Post ALERTS webhook if any failures were recorded (category: ALERTS)
if [[ -n "${ALERT_MSG:-}" && -n "${DISCORD_WEBHOOK_ALERTS:-}" ]]; then
    if [[ "$DRY_RUN" != "--dry-run" ]]; then
        msg="[ALERT $HOST] slimy-agent-finish failures: ${ALERT_MSG}agent=${AGENT}"
        curl -s -X POST "${DISCORD_WEBHOOK_ALERTS}" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$msg\"}" >/dev/null 2>&1 \
            && echo "[slimy-agent-finish] Posted ALERTS webhook" \
            || echo "[slimy-agent-finish] ALERTS webhook post failed (non-critical)"
    else
        echo "[slimy-agent-finish] DRY-RUN: would post ALERTS webhook: ${ALERT_MSG}"
    fi
fi

echo "[slimy-agent-finish] Finish automation complete."
