#!/usr/bin/env bash
# slimy-agent-finish.sh
# Single end-of-run automation entrypoint for Claude and Codex agents.
# Prevents recursion via SLIMY_AUTOFINISH_ACTIVE=1 env var.
#
# Usage:
#   slimy-agent-finish.sh --agent claude|codex|unknown [--repo /path/to/repo] [--summary "text"] [--dry-run] [--skip-compile] [--quiet]
#
# Flags:
#   --repo PATH   : limit to specific repo(s); skips auto-detection scan
#   --quiet       : suppress Discord ALERT posting (for SUCCESS path)
#   --skip-compile: skip kb-compile-if-needed
set -euo pipefail

# Disable interactive pager — wrapper-triggered runs have no TTY
export GIT_PAGER=cat
export PAGER=cat
# Fail-fast: prevent any interactive Git credential prompts (HTTPS remotes)
export GIT_TERMINAL_PROMPT=0
export GCM_INTERACTIVE=never

# Guard against recursion
if [[ "${SLIMY_AUTOFINISH_ACTIVE:-0}" == "1" ]]; then
    echo "[slimy-agent-finish] RECURSION GUARD: SLIMY_AUTOFINISH_ACTIVE=1 — exiting to prevent loop"
    exit 0
fi
export SLIMY_AUTOFINISH_ACTIVE=1

# Parse args
AGENT="unknown"
DRY_RUN=""
SKIP_COMPILE=""
QUIET=""
declare -a REPOS=()
SUMMARY=""
HOST=$(hostname -s)
TODAY=$(date +%Y-%m-%d)
TIMESTAMP=$(date -u +%Y%m%d-%H%M%S)
KB_ROOT="/home/slimy/kb"
KB_TOOLS="$KB_ROOT/tools"
ALLOWLIST_FILE="${DOC_SYNC_ALLOWLIST:-$KB_ROOT/config/doc-sync-allowlist.txt}"

is_allowlisted() {
    local path="$1"
    [[ ! -f "$ALLOWLIST_FILE" ]] && return 0
    while IFS= read -r line; do
        line="${line%%#*}"
        line="${line%"${line##*[![:space:]]}"}"
        line="${line#"${line%%[![:space:]]*}"}"
        [[ -z "$line" ]] && continue
        [[ "$path" == "$line" ]] && return 0
    done < "$ALLOWLIST_FILE"
    return 1
}

# Source webhook config if present
if [[ -f ~/.config/slimy/webhooks.env ]]; then
    source ~/.config/slimy/webhooks.env
fi

while [[ $# -gt 0 ]]; do
    case "$1" in
        --agent)
            AGENT="$2"; shift 2 ;;
        --repo)
            REPOS+=("$2"); shift 2 ;;
        --summary)
            SUMMARY="$2"; shift 2 ;;
        --dry-run)
            DRY_RUN="--dry-run"; shift ;;
        --skip-compile)
            SKIP_COMPILE="1"; shift ;;
        --quiet)
            QUIET="1"; shift ;;
        --)
            shift; break ;;
        -*)
            echo "[slimy-agent-finish] Unknown option: $1"; shift ;;
        *)
            break ;;
    esac
done

echo "[slimy-agent-finish] Starting finish automation..."
echo "[slimy-agent-finish] Agent: $AGENT | Host: $HOST | Dry-run: $DRY_RUN | Skip-compile: $SKIP_COMPILE | Quiet: $QUIET"
echo "[slimy-agent-finish] Repos: ${REPOS[*]:-none specified (will detect)}"

# Detect recently changed git repos only if none specified (bounded vs. full-scan mode)
if [[ ${#REPOS[@]} -eq 0 ]]; then
    echo "[slimy-agent-finish] No repos specified — detecting recently changed repos under /home/slimy and /opt/slimy..."
    declare -A SEEN=()
    # Look for git repos with commits in the last 24 hours
    for dir in /home/slimy /opt/slimy; do
        [[ -d "$dir" ]] || continue
        while IFS= read -r gitdir; do
            repo="${gitdir%/.git}"
            # Skip KB itself to avoid circular reference
            [[ "$repo" == "$KB_ROOT" ]] && continue
            # Avoid duplicates
            if [[ -z "${SEEN[$repo]:-}" ]]; then
                SEEN["$repo"]=1
                if ! is_allowlisted "$repo"; then
                    continue
                fi
                # Check if it has commits in last 24h
                if git --no-pager -C "$repo" log --since="24 hours ago" -q 2>/dev/null; then
                    REPOS+=("$repo")
                fi
            fi
        done < <(find "$dir" -maxdepth 4 -name ".git" -type d 2>/dev/null | sed 's/\/.git$//')
    done
    echo "[slimy-agent-finish] Detected ${#REPOS[@]} recently-changed repo(s): ${REPOS[*]:-none}"
fi

# Run kb-project-doc-sync for each repo
for repo in "${REPOS[@]}"; do
    if [[ -d "$repo" ]]; then
        echo "[slimy-agent-finish] Syncing project docs: $repo"
        bash "$KB_TOOLS/kb-project-doc-sync.sh" "$repo" "$DRY_RUN"
    else
        echo "[slimy-agent-finish] WARNING: repo not found: $repo"
    fi
done

# Write agent learnings KB raw note
RAW_LEARNINGS="$KB_ROOT/raw/agent-learnings/${TODAY}-${HOST}-${AGENT}-summary.md"
mkdir -p "$KB_ROOT/raw/agent-learnings"
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    cat > "$RAW_LEARNINGS" << EOF
---
name: ${TODAY}-${HOST}-${AGENT}-summary
description: ${AGENT} agent session summary for ${TODAY} on ${HOST}
type: agent-learning
---

# ${AGENT} Agent Session — ${TODAY} ${HOST}

> Agent: ${AGENT} | Host: ${HOST} | Timestamp: ${TIMESTAMP}

## Session Summary
${SUMMARY:-No summary provided.}

## Repos Touched
$(for repo in "${REPOS[@]:-}"; do echo "- $repo"; done)

## Notable Changes
${SUMMARY:-—}

## Next Steps
${SUMMARY:-—}

---
*Auto-generated by slimy-agent-finish.sh*
EOF
    echo "[slimy-agent-finish] Wrote agent learnings: $RAW_LEARNINGS"
else
    echo "[slimy-agent-finish] DRY-RUN: would write agent learnings to $RAW_LEARNINGS"
fi

# Write KB raw changelog note
RAW_CHANGELOG="$KB_ROOT/raw/changelogs/${TODAY}-${HOST}-project-changelog.md"
mkdir -p "$KB_ROOT/raw/changelogs"
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    cat > "$RAW_CHANGELOG" << EOF
---
name: ${TODAY}-${HOST}-project-changelog
description: Agent-triggered changelog for ${TODAY} on ${HOST}
type: changelog
---

# Changelog — ${TODAY} ${HOST}

> Agent: ${AGENT} | Host: ${HOST}

## Repos Updated
$(for repo in "${REPOS[@]:-}"; do
    if git --no-pager -C "$repo" rev-parse --git-dir >/dev/null 2>&1; then
        branch=$(git --no-pager -C "$repo" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "—")
        commit=$(git --no-pager -C "$repo" rev-parse --short HEAD 2>/dev/null || echo "—")
        msg=$(git --no-pager -C "$repo" log -1 --format="%s" 2>/dev/null || echo "—")
        echo "- \`$repo\` → \`$commit\` ($branch) — $msg"
    else
        echo "- $repo (non-git)"
    fi
done)

## Agent Summary
${SUMMARY:-—}

---
*Auto-generated by slimy-agent-finish.sh*
EOF
    echo "[slimy-agent-finish] Wrote changelog note: $RAW_CHANGELOG"
else
    echo "[slimy-agent-finish] DRY-RUN: would write changelog to $RAW_CHANGELOG"
fi

# Detect HTTPS GitHub remotes and skip push with warning (avoids interactive credential prompts)
is_https_github_remote() {
    local repo="$1"
    local remote_url
    remote_url=$(git -C "$repo" remote get-url origin 2>/dev/null || true)
    [[ "$remote_url" == https://github.com/* ]]
}

# Commit and push changed project repos (non-kb), track failures for ALERTS
ALERT_MSG=""
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    for repo in "${REPOS[@]:-}"; do
        [[ -d "$repo" ]] || continue
        [[ "$repo" == "$KB_ROOT" ]] && continue
        if ! is_allowlisted "$repo"; then
            echo "[slimy-agent-finish] SKIP commit: $repo not in allowlist"
            continue
        fi
        if git --no-pager -C "$repo" rev-parse --git-dir >/dev/null 2>&1; then
            REMOTE_URL=$(git --no-pager -C "$repo" remote get-url origin 2>/dev/null || true)
            if [[ -z "$REMOTE_URL" ]]; then
                echo "[slimy-agent-finish] SKIP commit: $repo has no remote (local-only)"
                continue
            fi
            changes=$(git --no-pager -C "$repo" status --porcelain 2>/dev/null || true)
            if [[ -n "$changes" ]]; then
                DOC_SYNC_MANAGED_FILES=("README.md" "CHANGELOG.md" "VERSION.md")
                NON_DOC_DIRTY=0
                while IFS= read -r line; do
                    [[ -z "$line" ]] && continue
                    fname="${line:3}"
                    is_doc=0
                    for doc_file in "${DOC_SYNC_MANAGED_FILES[@]}"; do
                        [[ "$fname" == "$doc_file" ]] && is_doc=1 && break
                    done
                    [[ "$is_doc" -eq 0 ]] && NON_DOC_DIRTY=1 && break
                done < <(git --no-pager -C "$repo" status --porcelain 2>/dev/null)
                if [[ "$NON_DOC_DIRTY" -eq 1 ]]; then
                    echo "[slimy-agent-finish] SKIP commit: $repo has non-doc dirty files (would pollute)"
                    continue
                fi
                echo "[slimy-agent-finish] Committing changes in $repo..."
                PRE_COMMIT_HASH=$(git --no-pager -C "$repo" rev-parse HEAD 2>/dev/null || true)
                AUTO_SYNC_COMMIT_MSG="docs: auto-sync project docs from ${HOST} ${TODAY}"
                if git --no-pager -C "$repo" add -A && git --no-pager -C "$repo" commit -m "$AUTO_SYNC_COMMIT_MSG" 2>/dev/null; then
                    if is_https_github_remote "$repo"; then
                        echo "[slimy-agent-finish] WARNING: HTTPS GitHub remote in $repo — reverting auto-sync commit (no push possible)"
                        git --no-pager -C "$repo" reset --soft "$PRE_COMMIT_HASH" 2>/dev/null
                        ALERT_MSG="${ALERT_MSG}push skipped (HTTPS): $repo; "
                    elif git --no-pager -C "$repo" push origin "$(git --no-pager -C "$repo" rev-parse --abbrev-ref HEAD)" 2>/dev/null; then
                        echo "[slimy-agent-finish] Pushed $repo"
                    else
                        echo "[slimy-agent-finish] WARNING: push failed for $repo — reverting auto-sync commit"
                        git --no-pager -C "$repo" reset --soft "$PRE_COMMIT_HASH" 2>/dev/null
                        ALERT_MSG="${ALERT_MSG}push failed, reverted: $repo; "
                    fi
                else
                    echo "[slimy-agent-finish] No changes to commit in $repo (commit returned no-op)"
                fi
            else
                echo "[slimy-agent-finish] No changes to commit in $repo"
            fi
        fi
    done
fi

# Commit and push KB changes created before child compile ran
# (child compile handles its own sync/push at end; this captures pre-child artifacts only)
if [[ "$DRY_RUN" != "--dry-run" ]]; then
    echo "[slimy-agent-finish] Committing KB changes..."
    # Check for any non-zero uncommitted changes (ignores child-cleaned temp files)
    KB_DIFF=$(cd "$KB_ROOT" && git --no-pager add -A && git --no-pager diff --cached --stat 2>&1 || true)
    if [[ -n "$KB_DIFF" && "$KB_DIFF" != " no changes added" ]]; then
        if git --no-pager -C "$KB_ROOT" commit -m "kb: autofile $AGENT $(date +%Y%m%d-%H%M%S)" 2>&1; then
            echo "[slimy-agent-finish] KB committed: ${KB_DIFF:0:80}"
        else
            echo "[slimy-agent-finish] WARNING: KB commit failed"
            ALERT_MSG="${ALERT_MSG}KB commit failed; "
        fi
    else
        echo "[slimy-agent-finish] No pre-child KB changes to commit"
    fi
    # Push any remaining local commits (child compile will have pushed its own)
    KB_PUSHED=$(cd "$KB_ROOT" && git --no-pager push origin main 2>&1 || true)
    if [[ "$KB_PUSHED" == *"error"* ]] || [[ "$KB_PUSHED" == *"fatal"* ]]; then
        echo "[slimy-agent-finish] WARNING: KB push had issues: ${KB_PUSHED:0:100}"
        ALERT_MSG="${ALERT_MSG}KB push had issues; "
    elif [[ -n "$KB_PUSHED" && "$KB_PUSHED" != *"Everything up-to-date"* ]]; then
        echo "[slimy-agent-finish] KB pushed: ${KB_PUSHED:0:80}"
    else
        echo "[slimy-agent-finish] KB push OK (up-to-date or synced by child)"
    fi
else
    echo "[slimy-agent-finish] DRY-RUN: would commit and push KB changes"
fi

# Run compile if not skipped, track failures for ALERTS
if [[ -z "$SKIP_COMPILE" && "$DRY_RUN" != "--dry-run" ]]; then
    echo "[slimy-agent-finish] Running compile check..."
    if ! bash "$KB_TOOLS/kb-compile-if-needed.sh" 2>&1; then
        echo "[slimy-agent-finish] WARNING: compile-if-needed returned non-zero"
        ALERT_MSG="${ALERT_MSG}compile-if-needed failed; "
    fi
elif [[ "$DRY_RUN" == "--dry-run" ]]; then
    echo "[slimy-agent-finish] DRY-RUN: skipping compile"
else
    echo "[slimy-agent-finish] SKIP_COMPILE set — skipping compile"
fi

# Post ALERTS webhook if any failures were recorded (category: ALERTS)
# Skip posting if --quiet flag is set (SUCCESS path)
if [[ -n "${ALERT_MSG:-}" && -n "${DISCORD_WEBHOOK_ALERTS:-}" && -z "$QUIET" ]]; then
    if [[ "$DRY_RUN" != "--dry-run" ]]; then
        msg="[ALERT $HOST] slimy-agent-finish failures: ${ALERT_MSG}agent=${AGENT}"
        curl -s -X POST "${DISCORD_WEBHOOK_ALERTS}" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"$msg\"}" >/dev/null 2>&1 \
            && echo "[slimy-agent-finish] Posted ALERTS webhook" \
            || echo "[slimy-agent-finish] ALERTS webhook post failed (non-critical)"
    else
        echo "[slimy-agent-finish] DRY-RUN: would post ALERTS webhook: ${ALERT_MSG}"
    fi
fi

echo "[slimy-agent-finish] Finish automation complete."
